- packages/nx-python/src/executors/add/executor.spec.ts
- packages/nx-python/src/graph/dependency-graph.spec.ts
- packages/nx-python/src/graph/dependency-graph.ts
Ensures that the dependency graph follows all arbitrary pip dependency groups.
Currently the dependency graph only respects the main depdencies and the dev dependency group. This expands it to support any arbitrary groups like poetry supports. e.g. `tool.poetry.group.example_group.dependencies`
Any dependencies added to custom groups appear in the dependency graph.
None
> feat(nx-python): follow all groups with dep graph

- packages/nx-python/README.md
- packages/nx-python/src/executors/build/executor.spec.ts
- packages/nx-python/src/executors/build/executor.ts
- packages/nx-python/src/executors/build/resolvers/project.ts
- packages/nx-python/src/executors/build/resolvers/types.ts
- packages/nx-python/src/executors/build/schema.d.ts
- packages/nx-python/src/executors/build/schema.json
- packages/nx-python/src/graph/dependency-graph.ts
Custom sources are not supported all packages will be specified as if they are in the default pypi configured on a consumers machine.
Custom sources can be specified and are injected into the build `pyproject.toml` as required by the `customSourceName` and `customSourceUrl` values specified within the build target options of a given project.
Fixes #40
> feat(nx-python): adds support for custom dependency sources

- package-lock.json
- package.json
- packages/nx-python/src/executors/build/executor.ts
- packages/nx-python/src/executors/build/resolvers/utils.ts
- packages/nx-python/src/executors/sls-deploy/executor.ts
- packages/nx-python/src/executors/sls-package/executor.ts
Currently, the `nx-python` project uses `fs-extra` without referencing it as a dependency, and pretty much the project uses a mix of `fs` and `fs-extra`, example: the `rmSync` should be replaced by `removeSync`.
Added `fs-extra` as a dependency and replaced all `rmSync` with `removeSync`.
I've tested all the operations, and all look good.
Fixes #53
> fix(nx-python): replace rmSync to fs-extra removeSync and add fs-extra as a dependency

- packages/nx-python/src/generators/project/__snapshots__/generator.spec.ts.snap
- packages/nx-python/src/generators/project/generator.ts
This PR changes the `nx-python` project generator to use the new Nx placeholders `{workspaceRoot}` and `{projectRoot}`.
currently, the `nx-python` project generator generates the project configuration using the old nx format.
Generate a new project using the new nx placeholders.
> feat(nx-python): added nx placeholders for nx-python generator project

- packages/nx-python/src/graph/dependency-graph.spec.ts
- packages/nx-python/src/graph/dependency-graph.ts
This PR fixes the dependency graph engine when there are Python projects not managed by the `@nxlv/python`
As described by @scottanderson42 in this comment https://github.com/lucasvieirasilva/nx-plugins/issues/101#issuecomment-1567423853, when there are other python projects in the same workspace that references local dependencies that are not managed by the `@nxlv/python` the dependency graph fails to calculate the dependencies, which results in a disconnection between the projects managed by `@nxlv/python`,  causing issues related to cache when dependencies are changed.
There is also an issue when the `pyproject.toml` is empty, in this case, the dependency graph also fails to calculate the dependencies.
This PR should handle those scenarios and provide the dependency graph correctly for …
> fix(nx-python): fix the dependency graph when there are Python projects not managed by the `@nxlv/python`

- packages/nx-python/src/executors/remove/executor.spec.ts
- packages/nx-python/src/executors/remove/executor.ts
- packages/nx-python/src/executors/utils/poetry.spec.ts
- packages/nx-python/src/executors/utils/poetry.ts
This PR adds the `--lock` command as part of the `poetry remove` command for poetry CLI version `1.5.0` or greater.
The `--lock` option in the remove command was added in the poetry `1.5.0` release, so, to make this plugin compatible with older versions, I've created logic to validate the poetry version before using the `--lock` option.
Currently, the remove executor always executes `poetry remove <package>`, however, when the shared virtual environment is used all the operations in the poetry sub-projects need to have the `--lock` to avoid applying the changes.
The changes need to be applied when the `@nxlv/python` updates the pyproject in the root.
If the poetry version is `1.5.0` or more and the project uses the shared virtual environment use the `--lock` option when the `remove` …
> feat(nx-python): add support for poetry remove --lock for poetry version >= 1.5.0

- packages/nx-python/src/dependency/update-dependency.ts
- packages/nx-python/src/executors/add/executor.spec.ts
- packages/nx-python/src/executors/remove/executor.spec.ts
- packages/nx-python/src/executors/update/executor.spec.ts
When the workspace is configured to use a shared virtual environment and the `add`, `update`, and `remove` is executed the root lock is being updated using `poetry update [pkgName]`.
The `poetry update` perform more tasks than just updates.
When the workspace is configured to use a shared virtual environment and the `add`, `update`, and `remove` is executed to update the root lock and the virtual environment is run `poetry lock --no-update` and `poetry install`.
> fix(nx-python): use poetry lock and poetry install when add/update/remove a package

- packages/nx-python/package.json
This PR changes the nx-python `package.json` to explicitly use `tslib` with caret.
Currently, when the project is built the `tslib` package is added with the static version of the repo's `package-lock.json`
The `tslib` library now is added to the dist `package.json` using `^2.3.0`.
Fixes #173
> fix(nx-python): add tslib explicitly to the package.json using caret

- package-lock.json
This PR syncs the `package-lock.json` version with node 18 + npm 9 setup.
Reference https://github.com/lucasvieirasilva/nx-plugins/pull/177
> chore(workspace): sync package-lock.json version with node 18 + npm 9

- packages/nx-python/src/executors/build/executor.spec.ts
- packages/nx-python/src/executors/build/resolvers/utils.ts
- packages/nx-python/src/graph/dependency-graph.ts
The build breaks when I depend on a local package with a `src` directory.
If I correctly specify `from="src"` in the local package's `pyproject.toml`, the build should succeed. When using a typical flat package structure, it works fine. i.e. like this
```
../lib
├── pyproject.toml
└── awesome_package/
└── __init__.py
```
I have a package: `my_package`. A snippet of its `pyproject.toml` is here:
```toml
[tool.poetry.dependencies.awsome_package]
path = "../lib"
develop = true
```
The local package that's being referred to has a directory structure like this.
```
../lib
├── pyproject.toml
└── src/
└── awesome_package/
└── __init__.py
```
The local package also has this snippet in its `pyproject.toml`
```toml
[[tool.poetry.packages]]
include = "awesome_package"
from = "src"
```
I think it …
> fix(nx-python): handle "from" for packages in pyproject.toml during the build process

- packages/nx-python/src/dependency/update-dependency.ts
- packages/nx-python/src/executors/add/executor.spec.ts
`add` does not relock root when project is grouped in root pyproject
`add` (and other like operators) should always relock the root
Fixes #194
> fix(nx-python): relock root when changing deps on grouped projects

- packages/nx-python/src/dependency/update-dependency.ts
- packages/nx-python/src/executors/add/executor.spec.ts
- packages/nx-python/src/executors/add/executor.ts
- packages/nx-python/src/executors/remove/executor.spec.ts
- packages/nx-python/src/executors/update/executor.spec.ts
- packages/nx-python/src/executors/update/executor.ts
- packages/nx-python/src/executors/utils/poetry.ts
currently, when there are more than 2 levels of local project dependencies, when a dependency is added to the 2 levels or deeper the nx python plugin uses `poetry update <lib>` to update to keep all the `poetry.lock` in sync.
however, the poetry update only works well for the first level, for all the others the poetry lock is not updated correctly.
the combination of `poetry lock` and only running `poetry install` when the root `pyproject.toml` is not present, updates the `poetry.lock` for all the levels of dependencies.
> fix(nx-python): replace poetry update with poetry lock and poetry install when adding a new package

- packages/nx-python/src/executors/build/executor.spec.ts
- packages/nx-python/src/executors/build/resolvers/locked.ts
- packages/nx-python/src/executors/utils/os.ts
Currently, when the projects has a local dependency and the build executor is called in a Windows machine the following error happen:
```
ERROR  pyproject.toml not found in /C:/Users/
```
That happens because the `@nxlv/python` plugin uses the output of the `poetry export` command, and the pattern for Mac/Linux is: `-e file:///Users/...` and for Windows is `-e file:///C:/Users/`.
The resolved location for Mac/Linux is `/Users/...` and `/C:/Users/` for Windows.
The resolved location should stay as-is for Mac/Linux and change from `/C:/Users/` to `C:/Users/` for Windows.
> fix(nx-python): resolve poetry export local path for windows

- packages/nx-python/src/generators/poetry-project/generator.ts
This PR changes the `nx-release-publish` default target to use `@nxlv/python:publish` executor
> fix(nx-python): use @nxlv/python:publish for nx-release-publish

- packages/nx-python/src/executors/publish/executor.ts
- packages/nx-python/src/executors/publish/schema.d.ts
- packages/nx-python/src/executors/publish/schema.json
This PR adds `dryRun` option to publish target (this option is also provided when you run `npm nx release publish --dry-run`)
> fix: add dry-run option to publish target

- packages/nx-python/src/dependency/update-dependency.ts
- packages/nx-python/src/executors/add/executor.spec.ts
- packages/nx-python/src/executors/add/executor.ts
- packages/nx-python/src/executors/build/executor.spec.ts
- packages/nx-python/src/executors/build/executor.ts
- packages/nx-python/src/executors/build/resolvers/project.ts
- packages/nx-python/src/executors/flake8/executor.spec.ts
- packages/nx-python/src/executors/flake8/executor.ts
- packages/nx-python/src/executors/install/executor.spec.ts
- packages/nx-python/src/executors/install/executor.ts
- packages/nx-python/src/executors/publish/executor.spec.ts
- packages/nx-python/src/executors/remove/executor.spec.ts
- packages/nx-python/src/executors/remove/executor.ts
- packages/nx-python/src/executors/ruff-check/executor.spec.ts
- packages/nx-python/src/executors/ruff-check/executor.ts
- packages/nx-python/src/executors/run-commands/executor.spec.ts
- packages/nx-python/src/executors/sls-deploy/executor.spec.ts
- packages/nx-python/src/executors/sls-deploy/executor.ts
- packages/nx-python/src/executors/sls-package/executor.spec.ts
- packages/nx-python/src/executors/sls-package/executor.ts
- packages/nx-python/src/executors/tox/executor.spec.ts
- packages/nx-python/src/executors/tox/executor.ts
- packages/nx-python/src/executors/update/executor.spec.ts
- packages/nx-python/src/executors/update/executor.ts
- packages/nx-python/src/executors/utils/poetry.ts
Hey!
First off, thank you for maintaining the python plugin for Nx. :) While doing some testing with the latest version of Nx, we found that this plugin does not work properly. This requires some changes because we removed a deprecated property from `context`. I've updated the references I found in this PR now.
Let me know if you have any questions or concerns, thanks!
Running this plugin with Nx 20 throws errors because of use of removed property on context.
Replaced `context.workspace` with `context.projectsConfigurations` which should be available since Nx 17. 
Fixes #
> fix(nx-python): remove deprecated property and replace with `context.projectsConfigurations`

- packages/nx-python/README.md
- packages/nx-python/src/executors/build/executor.spec.ts
- packages/nx-python/src/graph/dependency-graph.ts
- packages/nx-python/src/provider/resolver.ts
- packages/nx-python/src/provider/uv/build/resolvers/locked.ts
- packages/nx-python/src/provider/uv/provider.ts
- packages/nx-python/src/types.ts
This PR performs two fixes:
1. add `options.packageManager` to the nx.json plugins to detect `uv` non-workspace repos. #264 
2. Run `uv lock` command before running the `export` command in the build executor, when the export command is executed without a `uv.lock` the command fails.
1. Dependency Graph are not working for UV non-workspace projects.
2. For a brand new UV project without any dependency and with no `uv.lock` the build command fails.
The Dependency Graph should work for all the supported structures:
1. UV Workspace
2. UV Non-Workspaces
3. Poetry
Fixes #264
> UV Non-workspace Dependency Graph and UV Build without Lock file

- packages/nx-python/src/generators/release-version/release-version.ts
- packages/nx-python/src/provider/uv/provider.ts
The Nx release generator always pick Poetry provider for non-workspace UV projects.
the Nx release generator should resolve the right package manager.
Fixes #266
> Fix UV Package Manager Nx Release Feature

- packages/nx-python/executors.json
- packages/nx-python/src/executors/ruff-format/executor.spec.ts
- packages/nx-python/src/executors/ruff-format/executor.ts
- packages/nx-python/src/executors/ruff-format/schema.d.ts
- packages/nx-python/src/executors/ruff-format/schema.json
- packages/nx-python/src/generators/poetry-project/__snapshots__/generator.spec.ts.snap
- packages/nx-python/src/generators/poetry-project/generator.ts
- packages/nx-python/src/generators/utils.ts
- packages/nx-python/src/generators/uv-project/__snapshots__/generator.spec.ts.snap
- packages/nx-python/src/generators/uv-project/generator.ts
This PR adds a new executor `ruff-format` that wraps the `ruff format` command.
The user needs to create a Nx target with `@nxlv/python:run-commands` to run the ruff format.
The `ruff-format` should run the `ruff format` similarly as `ruff-check` executor, and if the user selects `ruff` as linter when creating a new python project, the `format` target needs to automatically added to the `project.json`
Fixes #269
> feat: add ruff-format executor for formatting files

- packages/nx-python/src/provider/poetry/build/resolvers/project.ts
- packages/nx-python/src/provider/poetry/provider.ts
This PR fixes the poetry's main dependency resolution for non-locked builds to support the explicit format `group.main` or implicit `poetry.dependencies`
As reported here https://github.com/lucasvieirasilva/nx-plugins/issues/270#issuecomment-2623555654, when changed from `[tool.poetry.dependencies]` to `[tool.poetry.group.main.dependencies]` the build target breaks.
The build target should work regardless the format of the main dependencies (implicit or explicit)
Fixes #270
> fix: handle optional poetry dependencies and improve dependency resolution logic

- packages/nx-python/src/executors/ruff-check/executor.spec.ts
- packages/nx-python/src/executors/ruff-check/executor.ts
- packages/nx-python/src/executors/ruff-check/schema.d.ts
- packages/nx-python/src/executors/ruff-check/schema.json
Allows a user to configure whether they want to fix lint errors via nx configurations by setting the fix property to true.
Users are unable to specify whether a lint task should fix errors via[ NX configuration](https://nx.dev/recipes/running-tasks/pass-args-to-commands#pass-args-in-the-projectjson-task-configuration)
Assume I have a `targetDefaults` in `nx.json` as follows:
```
"lint": {
"cache": true,
"configurations": {
"fix": {
"fix": true
}
},
"inputs": [
"default",
"{workspaceRoot}/eslint.config.mjs",
"{projectRoot}/eslint.config.mjs"
]
}
```
By specifying `fix` as true, when the ruff-check executor runs it will append the `--fix` flag.
I tried working around this via:
```
"configurations": {
"fix": {
"__unparsed__":"--fix"
}
}
```
however NX doesn't respect the inputs passed in and …
> feat(nx-python): add an optional fix option for the ruff-check executor

- packages/nx-python/src/generators/release-version/release-version.spec.ts
- packages/nx-python/src/generators/release-version/release-version.ts
This PR changes the release generator to use the `skipLockFileUpdate` option when provided 
The `skipLockFileUpdate` option is ignored and the lock files are updated anyway.
When the `skipLockFileUpdate` option is set to `true` the lock files should not be updated.
Fixes #276
> fix(nx-python): use option to skip lock file update during release

- packages/nx-python/src/graph/dependency-graph.spec.ts
- packages/nx-python/src/provider/uv/provider.ts
If workspace sources are listed (in `tool.uv.sources`) in the root `pyproject.toml`, they do not need to also be listed in a project's `pyproject.toml`.
If project A depends on project B, and the `tool.uv.sources` entry for project B is present only in the root `pyproject.toml`, no implicit dependency from A to B is created. 
If project A depends on project B, and the `tool.uv.sources` entry for project B is present only in the root `pyproject.toml`, an implicit dependency from A to B should be created.
> fix: read uv sources from root pyproject.toml

- packages/nx-python/README.md
- packages/nx-python/executors.json
- packages/nx-python/src/executors/lock/executor.spec.ts
- packages/nx-python/src/executors/lock/executor.ts
- packages/nx-python/src/executors/lock/schema.d.ts
- packages/nx-python/src/executors/lock/schema.json
- packages/nx-python/src/executors/sync/executor.spec.ts
- packages/nx-python/src/executors/sync/executor.ts
- packages/nx-python/src/executors/sync/schema.d.ts
- packages/nx-python/src/executors/sync/schema.json
- packages/nx-python/src/generators/poetry-project/__snapshots__/generator.spec.ts.snap
- packages/nx-python/src/generators/poetry-project/generator.ts
- packages/nx-python/src/generators/utils.ts
- packages/nx-python/src/generators/uv-project/__snapshots__/generator.spec.ts.snap
- packages/nx-python/src/provider/base.ts
- packages/nx-python/src/provider/poetry/provider.ts
- packages/nx-python/src/provider/uv/provider.ts
Add new executors for syncing and locking dependencies in Python projects:
- Introduced `@nxlv/python:sync` executor for synchronizing dependencies
- Introduced `@nxlv/python:lock` executor for locking dependencies
- Updated project generators to include these new executors in default targets
- Supports both Poetry and UV dependency management tools
- Provides options for verbose output, custom arguments, and cache directory configuration
Currently, only the `install` executor is available.
Be able to use all the following actions for all poetry versions:
| Action              | Poetry 1.x              | Poetry 2.x               | UV |
|---------------------|-------------------------|--------------------------|----|
| Install             | poetry install          | poetry install …
> feat(nx-python): add sync and lock executors

- packages/nx-python/src/generators/release-version/utils/package.ts
- packages/nx-python/src/provider/base.ts
- packages/nx-python/src/provider/poetry/provider.ts
- packages/nx-python/src/provider/uv/provider.ts
On the Python release-version generator, when the project dependency can't be resolved the process fails with an error:
```
NX   Running release version for project: test-python-version
test-python-version 🔍 Reading data for package "test-python-version" from apps/project-folder/projectname/pyproject.toml
test-python-version 📄 Resolved the current version as 1.0.0 from apps/project-folder/projectname/pyproject.toml
test-python-version 🚫 No changes were detected within version plans.
TypeError: Cannot read properties of null (reading 'tool')
at PoetryProvider.getDependencyMetadata (/projects-folder/repository/node_modules/.pnpm/@nxlv+python@20.7.0_nx@20.5.0_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.13___j6h6nrsonrsxpscyl3b24iikfq/packages/nx-python/src/provider/poetry/provi …
```
> fix: handle null values in dependency metadata retrieval

- package.json
- packages/nx-python/src/generators/migrate-to-shared-venv/__snapshots__/generator.spec.ts.snap
- packages/nx-python/src/generators/poetry-project/__snapshots__/generator.spec.ts.snap
- packages/nx-python/src/generators/poetry-project/files/base/pyproject.toml
- packages/nx-python/src/generators/poetry-project/files/pytest/tests/conftest.py
- packages/nx-python/src/generators/utils.ts
- packages/nx-python/src/generators/uv-project/__snapshots__/generator.spec.ts.snap
- packages/nx-python/src/generators/uv-project/files/base/pyproject.toml
- packages/nx-python/src/generators/uv-project/files/pytest/tests/conftest.py
This PR:
- Updated output paths in various generator configurations to use `{projectRoot}` for consistency.
- Reformatted `addopts` in `pyproject.toml` files to use multi-line strings for better readability.
- Adjusted pytest configuration in `conftest.py` files to remove unnecessary lines.
> feat(nx-python): update output paths and addopts formatting

- packages/nx-python/src/generators/uv-project/generator.spec.ts
- packages/nx-python/src/generators/uv-project/generator.ts
I missed a spot in https://github.com/lucasvieirasilva/nx-plugins/pull/286.
sorted-ness is not preserved in `project.dependencies`
sorted-ness is preserved in `project.dependencies`
> fix(nx-python): preserve sorted-ness in `project.dependencies`

- .cursor/mcp.json
- packages/nx-python/src/executors/ruff-check/executor.spec.ts
- packages/nx-python/src/executors/ruff-check/executor.ts
Whenever the `--fix` argument is provided with a bool (e.g. `--fix true`), nx passes them in the unparsed argument, which makes the ruff-check executor run the check with 2 `--fix`
Also, the ruff check doesn't support --fix true|false, it only supports `--fix`
The ruff-check executor should handle this scenario and only provide the `--fix` once, and use the `true` or `false` as a condition to send the `--fix` or not.
Fixes #299
> fix(nx-python): handle fix with boolean argument in ruff check

- packages/nx-python/README.md
- packages/nx-python/src/executors/build/executor.spec.ts
- packages/nx-python/src/executors/build/schema.d.ts
- packages/nx-python/src/executors/build/schema.json
- packages/nx-python/src/provider/poetry/provider.ts
- packages/nx-python/src/provider/uv/provider.ts
- Updated README.md to include `--format` option for specifying build format (sdist or wheel).
- Enhanced BuildExecutorSchema to include `format` property.
- Modified build logic in Poetry and UV providers to handle the new `format` option.
- Added tests for building Python projects in both wheel and sdist formats.
The build executor does not support the `--format` argument.
It should support `--format` argument with `wheel` or `sdist` value, when not provided, the package manager should generate both (default Poetry and Uv behavior)
Ref #301
> feat(nx-python): add support for build format options in Python executor

- packages/nx-python/src/executors/build/executor.spec.ts
- packages/nx-python/src/provider/uv/build/resolvers/utils.ts
When building a Python project with @nxlv/python using
```
"lockedVersions": false,
"bundleLocalDependencies": true
```
—and a local dependency that is both a direct requirement and a transitive requirement—nx run <proj>:build fails during uv build with:
```
ValueError: Duplicate path in field `tool.hatch.build.only-include`: <package>
```
The `@nxlv/python` should only include the package once.
Fixes #305
> fix(nx-python): check if hatch package exists before include

- packages/nx-python/src/release/version-actions.ts
- packages/nx-python/src/utils/path.ts
When UV workspaces are used with `nx release`, the @nxlv/python plugins attempt to add project-level lock files to the git staging files, but UV workspaces only have one single lock file in the root of the repo, which makes the nx release to fail with the following error:
```
NX   fatal: pathspec 'foo/uv.lock' did not match any files
```
The @nxlv/python plugin should check if the lock exists before processing it.
Fixes #309
> fix(nx-python): check for existence of project lock files before processing

- packages/nx-python/src/executors/publish/executor.ts
Errors are not being logged when the publish executor fails.
```log
ERROR  The publish command failed
———————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————
NX   Ran target nx-release-publish for project lib1 (487ms)
With additional flags:
--dryRun=true
✖  1/1 failed
✔  0/1 succeeded [0 read from cache]
```
The publish executor should log the error message in the console.
```log
ERROR  The publish command failed:
UV is not installed. Please install UV before running this command.
———————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————
NX   Ran target nx-release-publish for project lib1 (448ms)
With additional flags: …
```
> fix(nx-python): enhance error logging in publish executor to include error message

- .gitignore
- .vscode/settings.json
- packages/nx-python/src/executors/build/executor.spec.ts
- packages/nx-python/src/executors/build/executor.ts
- packages/nx-python/src/provider/poetry/build/resolvers/base.ts
- packages/nx-python/src/provider/poetry/build/resolvers/locked.ts
- packages/nx-python/src/provider/poetry/build/resolvers/project.ts
- packages/nx-python/src/provider/poetry/provider.ts
- packages/nx-python/src/provider/uv/build/resolvers/locked.ts
- packages/nx-python/src/provider/uv/build/resolvers/project.ts
- packages/nx-python/src/provider/uv/provider.ts
- packages/nx-python/src/provider/uv/types.ts
When using the `bundleDependencies` flag on the `@nxlv/python:build` executor with `lockedVersions=false`, optional dependencies specified as `extras` in local dependencies are not properly included in the bundled wheel metadata. While the optional dependencies are resolved and shown in the build log, they are not listed in the final `METADATA` file of the generated wheel package.
This issue occurs specifically when:
- `lockedVersions` is set to `false` (using `ProjectDependencyResolver`)
- A library specifies optional dependencies as `extras` in its `pyproject.toml` file  
- An application requires these `extras` in its `pyproject.toml`
- The build process with `bundleDependencies=true` is executed
Additionally, the Poetry dependency resolution logic had inconsistent handling of …
> fix: handling of optional dependencies on poetry and uv

- packages/nx-python/src/executors/run-commands/executor.ts
After the `installDependenciesIfNotExists` argument was added to the Nx Python plugin executor, the `@nxlv/python:run-commands` is passing the `installDependenciesIfNotExists` to the commands (e.g. pytest --installDependenciesIfNotExists)
Any additional arguments added to the `@nxlv/python:run-commands` shouldn't be passed to the commands.
Fixes #323
> fix: prevent additional arguments to be passed to run-commands executor
